<?xml version="1.0" encoding="UTF-8"?>
<doctest binary="all_features">
  <TestSuite>
    <TestCase name="lots of nested subcases" filename="subcases.cpp" line="0">

root
      <OverallResultsAsserts successes="0" failures="0"/>
    </TestCase>
    <TestCase name="subcases can be used in a separate function as well" filename="subcases.cpp" line="0">
      <SubCase name="from function..." filename="subcases.cpp" line="0">
        <Message>
          <Text>
            print me twice
          </Text>
        </Message>
        <SubCase name="sc1" filename="subcases.cpp" line="0">
          <Message>
            <Text>
              hello! from sc1
            </Text>
          </Message>
        </SubCase>
      </SubCase>
      <Message>
        <Text>
          lala
        </Text>
      </Message>
      <OverallResultsAsserts successes="0" failures="0"/>
    </TestCase>
    <TestCase name="  Scenario: vectors can be sized and resized" filename="subcases.cpp" line="0">
      <OverallResultsAsserts successes="0" failures="0"/>
    </TestCase>
    <TestCase name="test case should fail even though the last subcase passes" filename="subcases.cpp" line="0">
      <OverallResultsAsserts successes="0" failures="0"/>
    </TestCase>
    <TestCase name="fails from an exception but gets re-entered to traverse all subcases" filename="subcases.cpp" line="0">
      <OverallResultsAsserts successes="0" failures="0"/>
    </TestCase>
  </TestSuite>
  <OverallResultsAsserts successes="0" failures="0"/>
  <OverallResultsTestCases successes="5" failures="0"/>
</doctest>
Program code.
